
services:
  myapp:
    build: ../services/myapp
    container_name: myapp
    restart: unless-stopped
    depends_on:
      postgres-user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      LOCAL_BOT_TOKEN: ${LOCAL_BOT_TOKEN}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/config.yaml"
      POSTGRES_HOST: postgres-user-db
      POSTGRES_USER_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USERS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USERS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      PGUSER: ${USERS_PGUSER}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KEY: ${KEY}
      BOND_REPORT_SERVICE_HOST: bond-report-service
      BOND_REPORT_SERVICE_PORT: ${BOND_REPORT_SERVICE_PORT}
      TINKOFF_API_HOST: tinkoffapi_app
      TINKOFF_API_PORT: ${TINKOFF_API_PORT}

    volumes:
      - ../services/myapp/configs/config.yaml:/usr/local/src/configs/config.yaml:ro
    ports:
      - "${MYAPP_PORT}:8080"
    labels:
      logging: "true"
    networks:
      - myapp_network


  postgres-user-db:
    image: postgres:latest
    container_name: user_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USERS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      PGUSER: ${USERS_PGUSER}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_USER_PORT}:5432"
    networks:
      - myapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    

  redis:
    image: redis/redis-stack:latest
    container_name: redis-redis-stack
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_STACK_PORT}:8001"
    volumes:
      - redis_data_a:/data
    networks:
      - myapp_network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  migrator:
    build: ../tools/migrator
    container_name: migrator
    restart: no
    depends_on:
      postgres-user-db:
        condition: service_healthy
    environment:
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/config/config.yaml"
      MIGRATIONS_PATH: "/migrations"
      POSTGRES_HOST: postgres-user-db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_USERS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      POSTGRES_USER: ${POSTGRES_USERS_USER}
      PGUSER: ${USERS_PGUSER}

    volumes:
      - ../migrations/myapp/postgres:/usr/local/src/migrations:ro
      - ../tools/migrator/config/config.yaml:/usr/local/src/config/config.yaml:ro
    labels:
      logging: "true"
    networks:
      - myapp_network

  bond-report-service:
    build: ../services/bonds-report-service
    restart: unless-stopped
    container_name: bond-report-service-app
    depends_on:
      postgres-service-db:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/config.yaml"
      SBER_CONFIG_PATH: "/configs/sber.yaml"
      BOND_REPORT_SERVICE_PORT: ${BOND_REPORT_SERVICE_PORT}
      POSTGRES_HOST: postgres-service-db
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_USER: ${POSTGRES_SERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SERVICE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SERVICE_DB}
      PGUSER: ${SERVICE_PGUSER}
      CBR_HOST: cbr_app
      CBR_PORT: ${CBR_PORT}
      TINKOFF_API_HOST: tinkoffApi_app
      TINKOFF_API_PORT: ${TINKOFF_API_PORT}
      MOEX_API_HOST: moex_app
      MOEX_API_PORT: ${MOEX_API_PORT}
    volumes:
      - ../services/bonds-report-service/configs/config.yaml:/usr/local/src/configs/config.yaml:ro
      - ../services/bonds-report-service/configs/sber.yaml:/usr/local/src/configs/sber.yaml:ro
    ports:
      - "${BOND_REPORT_SERVICE_PORT}:8084"
    labels:
      logging: "true"
    networks:
      - myapp_network

  postgres-service-db:
    image: postgres:latest
    container_name: service_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_SERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SERVICE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SERVICE_DB}
      PGUSER: ${SERVICE_PGUSER}
    volumes:
      - postgres_service_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_SERVICE_PORT}:5432"
    networks:
      - myapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  cbr_app:
    build: ../services/cbr
    container_name: cbr_app
    restart: unless-stopped
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/local.yaml"
      CBR_PORT: "${CBR_PORT}"
    volumes:
      - ../services/cbr/configs/local.yaml:/usr/local/src/configs/local.yaml:ro
    ports:
      - "${CBR_PORT}:8083"
    labels:
      logging: "true"
    networks:
      - myapp_network

  tinkoffapi_app:
    build: ../services/tinkoffApi
    container_name: tinkoffapi_app
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/local.yaml"
      TINKOFF_CONFIG_PATH: "/configs/tinkoffApiConfig.yaml"
      TINKOFF_API_PORT: ${TINKOFF_API_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KEY: ${KEY}
    volumes:
      - ../services/tinkoffApi/configs/local.yaml:/usr/local/src/configs/local.yaml:ro
      - ../services/tinkoffApi/configs/tinkoffApiConfig.yaml:/usr/local/src/configs/tinkoffApiConfig.yaml:ro
    ports:
      - "${TINKOFF_API_PORT}:8082"
    labels:
      logging: "true"
    networks:
      - myapp_network

  moex_app:
    build: ../services/moexApi
    container_name: moex_app
    restart: unless-stopped
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/local.yaml"
      MOEX_API_PORT: ${MOEX_API_PORT}
    volumes:
      - ../services/moexApi/configs/local.yaml:/usr/local/src/configs/local.yaml:ro
    ports:
      - "${MOEX_API_PORT}:8083"
    labels:
      logging: "true"
    networks:
      - myapp_network

  opensearch-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1,opensearch-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=02newzXze7bqsw9eqA    # Sets the demo admin user password when using demo configuration, required for OpenSearch 2.12 and later
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - myapp_network # All of the containers will join the same Docker bridge network


  opensearch-node2:
    image: opensearchproject/opensearch:latest # This should be the same image used for opensearch-node1 to avoid issues
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=02newzXze7bqsw9eqA
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - myapp_network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - myapp_network

  filebeat:
    image: opensearchproject/filebeat:2.12.0
    container_name: filebeat
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./setup/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    restart: unless-stopped
    networks:
    - myapp_network
    

networks:
  myapp_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data_a:
  postgres_service_data:
  opensearch-data1:
  opensearch-data2: