x-logging: &logging
  logging:
    driver: "fluentd"
    options:
      fluentd-address: "fluentd:24224"
      tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"


services:
  myapp:
    build: ../services/myapp
    <<: *logging
    container_name: myapp
    restart: unless-stopped
    depends_on:
      postgres-user-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      LOCAL_BOT_TOKEN: ${LOCAL_BOT_TOKEN}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/config.yaml"
      POSTGRES_HOST: postgres-user-db
      POSTGRES_USER_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USERS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USERS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      PGUSER: ${USERS_PGUSER}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KEY: ${KEY}
      BOND_REPORT_SERVICE_HOST: bond-report-service
      BOND_REPORT_SERVICE_PORT: ${BOND_REPORT_SERVICE_PORT}
      TINKOFF_API_HOST: tinkoffapi_app
      TINKOFF_API_PORT: ${TINKOFF_API_PORT}

    volumes:
      - ../services/myapp/configs/config.yaml:/usr/local/src/configs/config.yaml:ro
    ports:
      - "${MYAPP_PORT}:8080"
    networks:
      - myapp_network


  postgres-user-db:
    image: postgres:latest
    container_name: user_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USERS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      PGUSER: ${USERS_PGUSER}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_USER_PORT}:5432"
    networks:
      - myapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack:latest
    container_name: redis-redis-stack
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_STACK_PORT}:8001"
    volumes:
      - redis_data_a:/data
    networks:
      - myapp_network
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$$REDIS_PASSWORD", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  migrator:
    build: ../tools/migrator
    <<: *logging
    container_name: migrator
    restart: no
    depends_on:
      postgres-user-db:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    environment:
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/config/config.yaml"
      MIGRATIONS_PATH: "/migrations"
      POSTGRES_HOST: postgres-user-db
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: ${POSTGRES_USERS_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      POSTGRES_USER: ${POSTGRES_USERS_USER}
      PGUSER: ${USERS_PGUSER}

    volumes:
      - ../migrations/myapp/postgres:/usr/local/src/migrations:ro
      - ../tools/migrator/config/config.yaml:/usr/local/src/config/config.yaml:ro
    networks:
      - myapp_network

  bond-report-service:
    build: ../services/bonds-report-service
    <<: *logging
    restart: unless-stopped
    container_name: bond-report-service-app
    depends_on:
      postgres-service-db:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/config.yaml"
      SBER_CONFIG_PATH: "/configs/sber.yaml"
      BOND_REPORT_SERVICE_PORT: ${BOND_REPORT_SERVICE_PORT}
      POSTGRES_HOST: postgres-service-db
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_USER: ${POSTGRES_SERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SERVICE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SERVICE_DB}
      PGUSER: ${SERVICE_PGUSER}
      CBR_HOST: cbr_app
      CBR_PORT: ${CBR_PORT}
      TINKOFF_API_HOST: tinkoffApi_app
      TINKOFF_API_PORT: ${TINKOFF_API_PORT}
      MOEX_API_HOST: moex_app
      MOEX_API_PORT: ${MOEX_API_PORT}
    volumes:
      - ../services/bonds-report-service/configs/config.yaml:/usr/local/src/configs/config.yaml:ro
      - ../services/bonds-report-service/configs/sber.yaml:/usr/local/src/configs/sber.yaml:ro
    ports:
      - "${BOND_REPORT_SERVICE_PORT}:8084"
    networks:
      - myapp_network

  postgres-service-db:
    image: postgres:latest
    container_name: service_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_SERVICE_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SERVICE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SERVICE_DB}
      PGUSER: ${SERVICE_PGUSER}
    volumes:
      - postgres_service_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_SERVICE_PORT}:5432"
    networks:
      - myapp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  cbr_app:
    build: ../services/cbr
    <<: *logging
    container_name: cbr_app
    restart: unless-stopped
    depends_on:
      fluentd:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/local.yaml"
      CBR_PORT: "${CBR_PORT}"
    volumes:
      - ../services/cbr/configs/local.yaml:/usr/local/src/configs/local.yaml:ro
    ports:
      - "${CBR_PORT}:8083"
    networks:
      - myapp_network

  tinkoffapi_app:
    build: ../services/tinkoffApi
    <<: *logging
    container_name: tinkoffapi_app
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      fluentd:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/local.yaml"
      TINKOFF_CONFIG_PATH: "/configs/tinkoffApiConfig.yaml"
      TINKOFF_API_PORT: ${TINKOFF_API_PORT}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      KEY: ${KEY}
    volumes:
      - ../services/tinkoffApi/configs/local.yaml:/usr/local/src/configs/local.yaml:ro
      - ../services/tinkoffApi/configs/tinkoffApiConfig.yaml:/usr/local/src/configs/tinkoffApiConfig.yaml:ro
    ports:
      - "${TINKOFF_API_PORT}:8082"
    networks:
      - myapp_network

  moex_app:
    build: ../services/moexApi
    <<: *logging
    container_name: moex_app
    restart: unless-stopped
    depends_on:
      fluentd:
        condition: service_healthy
    environment:
      ENV: ${ENV}
      ROOT_PATH: "/usr/local/src"
      CONFIG_PATH: "/configs/local.yaml"
      MOEX_API_PORT: ${MOEX_API_PORT}
    volumes:
      - ../services/moexApi/configs/local.yaml:/usr/local/src/configs/local.yaml:ro
    ports:
      - "${MOEX_API_PORT}:8083"
    networks:
      - myapp_network


  opensearch-node1: 
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    restart: always
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts-opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xms512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - myapp_network


  opensearch-node2: 
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    restart: always
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts-opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xms512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - myapp_network

  opensearch-dashboards:
    build:
      context: ./setup/opensearch-dashboards/
    container_name: opensearch-dashboards
    restart: always
    ports: 
      - "127.0.0.1:5601:5601"  
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200","http://opensearch-node2:9200"]'  
    networks:
      - myapp_network


  fluentd:
    build:
      context: ./setup/fluentd/
    container_name: fluentd
    restart: always
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9880:9880" 
    volumes:
      - ./setup/fluentd/fluentd.conf:/fluentd/etc/fluent.conf
    networks:
      - myapp_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep green"]
      interval: 10s
      retries: 5
      timeout: 5s
 

networks:
  myapp_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data_a:
  postgres_service_data: