clients: 
  bondReportServiceHost: "localhost:8084"
  telegramHost: "api.telegram.org"
  tinkoffApiHost: "localhost:8082"
dbType: "postgreSQL" # "postgreSQL" , "SQLite"
storageSQLLitePath: "/data/sqlite/storage.db"
migrationsSqllitePath: "/migrations/sqlite"
migrationsPostgresPath: "/migrations/postgres"
postgresHost:
  host: ""
  user: ""
  password: ""
  dbname: ""
  port: 5433
  sslmode: "disable"
redis:
  addr: ""
  password: ""
  user: ""
  db: 0
  max_retries: 5
  dial_timeout: 10s
  timeout: 5s



