env: local
dbType: "postgreSQL" # "postgreSQL" , "SQLite"
serviceStorageSQLLitePath: "/data/sqlite/service_storage.db"
postgresHost:
  host: "localhost"
  user: "user"
  password: "parol"
  dbname: "service"
  port: 5432
  sslmode: "disable"



