services:
  myapp:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres-user-db
      - redis
    environment:
      ROOT_PATH: "/usr/local/src"
      LOCAL_BOT_TOKEN: ${LOCAL_BOT_TOKEN}
      KEY: ${KEY}
      POSTGRES_HOST: postgres-user-db
      POSTGRES_PASSWORD: ${MYAPP_DB_PASSWORD}
      POSTGRES_DB: ${MYAPP_POSTGRES_DB}
      POSTGRES_USER: ${MYAPP_POSTGRES_USER}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - ./configs/config.yaml:/usr/local/src/configs/config.yaml:ro
    ports:
      - "8080:8080"
    networks:
      - myapp_network

  postgres-user-db:
    image: postgres:latest
    container_name: user_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${MYAPP_DB_PASSWORD}
      POSTGRES_DB: ${MYAPP_POSTGRES_DB}
      POSTGRES_USER: ${MYAPP_POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    networks:
      - myapp_network

  redis:
    image: redis/redis-stack:latest
    container_name: redis-redis-stack
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data_a:/data
    networks:
      - myapp_network


networks:
  myapp_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data_a: